# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

FROM mssql-python:latest

# Copy the LMS-DS Loader in the container
COPY tmp/lms-ds-loader/ /app/lms-ds-loader

# TODO: The above should be ignoring the .env file due to a .dockerignore file,
# but that's not working properly. I had to manually remove the .env file.

# Copy the sample files
COPY tmp/sample-out/ /app/data

# Prep filesystem
COPY entrypoint.sh /app
USER root
RUN chmod a+x /app/*.sh && \
    mkdir /app/out && \
    chown mssql /app -R

# Change back to the MSSQL user
USER mssql

# Install the loader
WORKDIR /app/lms-ds-loader
RUN PATH="$HOME/.poetry/bin:$PATH" && \
    poetry install

# Run the tests
CMD /app/entrypoint.sh
