# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

FROM edfialliance/mssql-python:latest

# Copy the source files into the container
COPY tmp/edfi_lms_ds_loader /app/edfi_lms_ds_loader
COPY tmp/poetry.lock /app/poetry.lock
COPY tmp/pyproject.toml /app/pyproject.toml
COPY tmp/README.md /app/README.md
COPY tmp/sample-out /app/sample-out

# Prep filesystem
COPY entrypoint.sh /app
USER root
RUN chmod a+x /app/*.sh && \
    mkdir /app/out && \
    chown mssql /app -R

# Change back to the MSSQL user
USER mssql

# Install the loader
WORKDIR /app
RUN PATH="$HOME/.poetry/bin:$PATH" && \
    poetry env use 3.9 && \
    poetry install

# Run the tests
CMD /app/entrypoint.sh & /opt/mssql/bin/sqlservr
