BEGIN TRANSACTION
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'fizz.Assignment') AND name = N'UX_Assignment_Id')
    CREATE UNIQUE NONCLUSTERED INDEX UX_Assignment_Id ON [fizz].[Assignment]
    (Id) WITH (PAD_INDEX = ON, FILLFACTOR = 75, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
    GO
COMMIT

BEGIN TRANSACTION
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'fizz.AssignmentSubmission') AND name = N'UX_AssignmentSubmission_Id')
    CREATE UNIQUE NONCLUSTERED INDEX UX_AssignmentSubmission_Id ON [fizz].[AssignmentSubmission]
    (Id) WITH (PAD_INDEX = ON, FILLFACTOR = 75, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
    GO
COMMIT

BEGIN TRANSACTION
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'fizz.LMSGrade') AND name = N'UX_LMSGrade_Id')
    CREATE UNIQUE NONCLUSTERED INDEX UX_LMSGrade_Id ON [fizz].[LMSGrade]
    (Id) WITH (PAD_INDEX = ON, FILLFACTOR = 75, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
    GO
COMMIT

BEGIN TRANSACTION
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'fizz.LMSSection') AND name = N'UX_LMSSection_Id')
    CREATE UNIQUE NONCLUSTERED INDEX UX_LMSSection_Id ON [fizz].[LMSSection]
    (Id) WITH (PAD_INDEX = ON, FILLFACTOR = 75, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
    GO
COMMIT

BEGIN TRANSACTION
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'fizz.LMSUser') AND name = N'UX_LMSUser_Id')
    CREATE UNIQUE NONCLUSTERED INDEX UX_LMSUser_Id ON [fizz].[LMSUser]
    (Id) WITH (PAD_INDEX = ON, FILLFACTOR = 75, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
    GO
COMMIT

BEGIN TRANSACTION
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'fizz.LMSUserActivity') AND name = N'UX_LMSUserActivity_Id')
    CREATE UNIQUE NONCLUSTERED INDEX UX_LMSUserActivity_Id ON [fizz].[LMSUserActivity]
    (Id) WITH (PAD_INDEX = ON, FILLFACTOR = 75, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
    GO
COMMIT

BEGIN TRANSACTION
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'fizz.LMSUserAttendanceEvent') AND name = N'UX_LMSUserAttendanceEvent_Id')
    CREATE UNIQUE NONCLUSTERED INDEX UX_LMSUserAttendanceEvent_Id ON [fizz].[LMSUserAttendanceEvent]
    (Id) WITH (PAD_INDEX = ON, FILLFACTOR = 75, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
    GO
COMMIT

BEGIN TRANSACTION
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'fizz.LMSUserLMSSectionAssociation') AND name = N'UX_LMSUserLMSSectionAssociation_Id')
    CREATE UNIQUE NONCLUSTERED INDEX UX_LMSUserLMSSectionAssociation_Id ON [fizz].[LMSUserLMSSectionAssociation]
    (Id) WITH (PAD_INDEX = ON, FILLFACTOR = 75, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
    GO
COMMIT

