name: Repository Security Scan
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  edfi-repo-scan:
    name: Scan GitHub Actions and BIDI attacks
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@main

  dependency-review:
    name: Scan repo dependencies for security issues
    runs-on: ubuntu-latest
    # Dependency review needs to compare with another branch, so it should only
    # run on PR. Keeping it as a separate workflow because there is no way to
    # specify which path, and thus does not make sense inside of a
    # package-specific workflow.
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Dependency Review ("Dependabot on PR")
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0
